FROM openjdk:17-jdk-slim
LABEL "org.opencontainers.image.authors"="prateekarya100@gmail.com"
COPY target/Accounts-0.0.1-SNAPSHOT.jar "Accounts-0.0.1-SNAPSHOT.jar"
ENTRYPOINT ["java","-jar","Accounts-0.0.1-SNAPSHOT.jar"]