server:
  port: 8090

spring:
  datasource:
#    url: "jdbc:mysql://localhost:3306/microservices"
#    username: "root"
#    password: "root"
#    driver-class-name: com.mysql.cj.jdbc.Driver

   url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:microservices}"
   username: ${MYSQL_USER:root}
   password: ${MYSQL_PASSWORD:root}
   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
