FROM openjdk:17-jdk-slim
LABEL "org.opencontainers.image.authors"="prateekarya100@gmail.com"
COPY target/Cards-0.0.1-SNAPSHOT.jar "Cards-0.0.1-SNAPSHOT.jar"
ENTRYPOINT ["java","-jar","Cards-0.0.1-SNAPSHOT.jar"]