FROM openjdk:17-jdk-slim
LABEL "org.opencontainers.image.authors"="prateekarya100@gmail.com"
COPY target/Loans-0.0.1-SNAPSHOT.jar "Loans-0.0.1-SNAPSHOT.jar"
ENTRYPOINT ["java","-jar","Loans-0.0.1-SNAPSHOT.jar"]