
server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/microservices"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: 2.5

application:
  developer: PRATEEK ARYA
contactDetails:
  mobile: 9650841442
  email: prateekarya100@gmail.com

accounts:
  message: "Welcome to EazyBank Accounts Restful webservices related APIs"
  contactDetails:
    mobile: "9650841442"
    email: "prateekarya100@gmail.com"
  onCallSupport:
    - 9650841442
    - 9389998268